#!/usr/bin/env bash
# Configuring a new ubuntu machine by installing
# nginx, it should be listening on port 80
# Serve a page that returns a Hello World string
#


echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
         sudo apt-get install nginx -y

echo -e "\n Sets up  minor small things.\n"

# starts  nginx serviers
sudo service nginx start

# allows  nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Gives user ownership to the website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backing the up default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creats  new index
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# Set up or redirect_me to a youtube video
sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx restart

echo -e "\nCompleted.\n"
