#!/usr/bin/env bash
# Install and configure HAProxy on Ubuntu

# Update and install HAProxy
sudo apt-get update -y
sudo apt-get install -y haproxy

# Backup default HAProxy config
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Set up HAProxy configuration
sudo tee /etc/haproxy/haproxy.cfg > /dev/null << 'EOF'
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend solutionexpo.tech
    bind *:80
    default_backend solutionexpo.tech

backend ismaelkiprop.tech
    balance roundrobin
    server 477189-web-01 100.25.158.77:80 check
    server 477189-web-02 100.25.111.97:80 check
EOF

# Enable HAProxy to be managed by init script
echo "ENABLED=1" | sudo tee /etc/default/haproxy > /dev/null

# Restart HAProxy service
sudo service haproxy restart
